apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app: welcome-php
  name: welcome-php
  namespace: welcome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-php
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: welcome-php
    spec:
      containers:
      - image: quay.io/redhatworkshops/welcome-php:latest
        name: welcome-php
        resources: {}
status: {}
